#!/bin/bash

BUILD_DIR=build

xcrun xcodebuild build-for-testing \
  -configuration Debug \
  -workspace Confetti.xcworkspace \
  -sdk iphoneos \
  -scheme Confetti \
  -derivedDataPath $BUILD_DIR

appcenter test run xcuitest \
  --app "ContinuousDeliveryInc/Confetti" \
  --devices "ContinuousDeliveryInc/smoke-test-device-set" \
  --app-path $APPCENTER_OUTPUT_DIRECTORY/Confetti.ipa \
  --test-series "smoke-tests" \
  --locale "en_US" \
  --build-dir $BUILD_DIR/Build/Products/Debug-iphoneos \
  --token $APPCENTER_API_TOKEN
