#!/bin/bash

export TEST_BUILD_DIR=test-builds
mkdir -p $TEST_BUILD_DIR
xcrun xcodebuild build-for-testing \
  -configuration Debug \
  -workspace Confetti.xcworkspace \
  -sdk iphoneos \
  -scheme Confetti \
  -derivedDataPath $TEST_BUILD_DIR

appcenter test run xcuitest \
  --app "ContinuousDeliveryInc/Confetti" \
  --devices "ContinuousDeliveryInc/smoke-test-device-set" \
  --app-path $APPCENTER_OUTPUT_DIRECTORY/Confetti.ipa \
  --test-series "smoke-tests" \
  --locale "en_US" \
  --build-dir $TEST_BUILD_DIR/Build/Products/Debug-iphoneos \
  --token $APPCENTER_API_TOKEN

rm -fr $TEST_BUILD_DIR
